# Generated by Django 3.2.6 on 2024-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=100),
        ),
    ]
