# Generated by Django 3.2.6 on 2024-03-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240331_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='paid',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
