# Generated by Django 3.2.6 on 2024-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20240321_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interview',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
