# Generated by Django 3.2.6 on 2024-03-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interview',
            new_name='int_date',
        ),
        migrations.AddField(
            model_name='user',
            name='int_link',
            field=models.TextField(blank=True),
        ),
    ]
